name: Deploy Vanilla JS to Pages

on:
  push:
    branches: ["master"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Inject Secrets into watchlist/app.js
        run: |
          sed -i "s|INJECT_API_KEY_HERE|${{ secrets.SECRET_API_KEY }}|g" watchlist/app.js
          sed -i "s|INJECT_GAS_URL_HERE|${{ secrets.GOOGLE_APP_SCRIPT_URL }}|g" watchlist/app.js
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4